server:
  port: 8001
spring:
  application:
    name: service-edu
  profiles: #激活的环境
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/education?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #返回的时间格式
    time-zone: Asia/Shanghai #时区
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #日志，SQL语句输出到控制台
    map-underscore-to-camel-case: true
  type-aliases-package: com.wuzhangze.eduservice.entity #配置别名
  global-config:
    # 逻辑删除配置
    db-config:
      logic-delete-field: isDeleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
