#server:
#  port: 8003
#spring:
#  application:
#    name: service-vod
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#  profiles:
#    active: dev
#  servlet:
#    multipart:
#      max-file-size: 1024MB
#      max-request-size: 1024MB
#aliyun:
#  vod:
#    file:
#      keyId: xxxx
#      keySecret: xxxx
#
#management:
#  health:
#    redis:
#      enabled: false
#  endpoints:
#    web:
#      exposure:
#        include: '*'