#server:
#  port: 8007
#spring:
#  application:
#    name: service-order
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#        endpoint:
#    sentinel:
#      transport:
#        dashboard: localhost:8080
#        port: 8719
#  profiles: #激活的环境
#    active: dev
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/education?serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss #返回的时间格式
#    time-zone: Asia/Shanghai #时区
#  redis:
#    host: localhost
#    port: 6379
#    timeout: 5000
#    database: 0
#
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #日志，SQL语句输出到控制台
#    map-underscore-to-camel-case: true
#  type-aliases-package: com.wuzhangze.order.entity #配置别名
#  global-config:
#    # 逻辑删除配置
#    db-config:
#      logic-delete-field: isDeleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#  mapper-locations: classpath*:com/wuzhangze/order/mapper/**/*.xml
#
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#feign:
#  sentinel:
#    enabled: true
#
#ribbon:
#  ReadTimeout: 50000
#  ConnectTimeout: 50000
#
#wx:
#  open:
#    # 关联的公众号appid
#    appId: wx74862e0dfcf69954
#    # 商户号
#    partner: 1558950191
#    # 商户key
#    partnerKey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
#    # 回调地址
#    notifyUrl: http://guli.shop/api/order/weixinPay/weixinNotify