#server:
#  port: 8005
#spring:
#  application:
#    name: service-sms
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#    sentinel:
#      transport:
#        dashboard: localhost
#        port: 8719
#  redis:
#    host: localhost
#    port: 6379
#    database: 0
#    timeout: 10000
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#
#sms-config:
#  secretId: AKIDmLnysVrxmJZZHislOkqfDUUEhsmOkqeB
#  secretKey: GG0UgcHfmdCUVFiupSpvkKdgRv86mBJB
#  sdkAppId: '1400569767'
#  signName: 奋斗小吴
#  templateId: '1108047'
#
